# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - fowlart-simple-java-app

on:
  push:
    branches:
      - master_2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Copy files
        uses: ulaval/azure-blob-copy-action@v1
        with:
          action: upload
          connection_string: https://fowlartstor.blob.core.windows.net/settings?sp=r&st=2023-05-10T10:29:01Z&se=2025-03-01T19:29:01Z&spr=https&sv=2022-11-02&sr=c&sig=bdcioggujf9aSBmJLhsPAA7k4imXUCyuF9%2Bwe8gQk48%3D
          container_name: settings
          local_directory: dist
          http_headers: |
            - glob: "**/*.????????.*"
              headers:
                Cache-Control: public, max-age=604800, immutable
            
            - glob: "**/*"
              headers:
                Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate

      - name: Build with Maven
        run: mvn clean scala:compile package spring-boot:repackage && jar tf target/app-1.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FowlartTgBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7E05E7B8E1F84942AD86A094E1DA8623 }}
          package: '*.jar'

      - name: Java version
        run: java -version

      - name: Run jar file
        run: java -jar -Dspring.profiles.active=prod /home/runner/work/fowlart_commerce_telegram/fowlart_commerce_telegram/app-1.jar